#!/bin/bash
# Get the directory where this bash script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
grep "      1     -" outfile* | sort -n -k 4,4 | python3 "$SCRIPT_DIR/bf.py"
